#!/bin/bash
#
# Forked from statianzo/dokku-shoreman

app="$1"; image="app/$app"

read -d '' shoreman <<'EOF'
set -e
export home=/app
for file in \$home/.profile.d/*; do source \$file; done
hash -r
cd \$home
export RUNTIME_ENV=\${RACK_ENV:-\$RAILS_ENV} # TODO make this better

procfile="Procfile"

if [ -f "Procfile.\$RUNTIME_ENV" ]; then
  procfile="Procfile.\$RUNTIME_ENV"
elif [ -f "Procfile" ]; then
  procfile="Procfile"
else
  exit 0
fi

while read line || [ -n "\$line" ]; do
  name=\${line%%:*}
  command=\${line#*: }
  echo "Starting \${name}..."
  sh -c "\${command} | sed -e 's/^/\${name}| /'" &
done < "\$procfile"


onexit() {
  echo SIGINT received
  echo sending SIGTERM to all processes
  children=\$(ps --ppid=\$\$ -o pid='')
  kill -- \$children &> /dev/null
  sleep 1
}
trap onexit SIGTERM SIGINT EXIT

wait
EOF

set -e

echo "-----> Injecting Shoreman ..."

id=$(echo "$shoreman" | docker run -i -a stdin $image /bin/bash -c "cat > /start")
test $(docker wait $id) -eq 0
docker commit $id $image > /dev/null
